application: o-spear
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /google5defcf808435d2a9.html
  static_files: static/google5defcf808435d2a9.html
  upload: static/google5defcf808435d2a9.html

- url: /s/
  static_dir: static/web

- url: /.*
  script: main.py
